# Usage:
# python -m pre_commit run --all-files

repos:
  # Formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.0
    hooks:
      - id: clang-format
        files: \.(cpp|cc|cxx|hh|hpp|h)$

  # Linting & Naming
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        files: \.(cpp|cc|cxx)$
        args:
          - "--extra-arg=-std=c++23"
          - "--extra-arg=-Iinclude"
        additional_dependencies: ["clang-tidy"]
